server:
  port: 8001

mybatis:
 config-location: classpath:mybatis/mybatis-config.xml
 type-aliases-package: com.kuang.springcloud.pojo
 mapper-locations: classpath:mybatis/mapper/*.xml

spring:
 application:
  name: springcloud-provider-dept
 datasource:
  type: com.alibaba.druid.pool.DruidDataSource # 数据源
  driver-class-name: org.gjt.mm.mysql.Driver # mysql驱动
  url: jdbc:mysql://localhost:3306/ssmbuild #数据库名称
  username: root
  password: root


eureka:
  client:
   service-url:
    defaultZone: http://192.168.177.1:7001/eureka/,http://192.168.177.1:7002/eureka/
